name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      # 1. Checkout your repository
      - uses: actions/checkout@v4

      # 2. Set up Java (make sure this matches your code requirements)
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'zulu'

      # 3. Set up Gradle (no wrapper)
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582
        with:
          gradle-version: '4.5'

      # 4. Build the project (this generates your JAR file in build/libs)
      - name: Build with Gradle
        run: gradle build

      # 5. Upload the built JAR as an artifact
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}
          path: build/libs/*.jar
