name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      # 1. Checkout source code
      - uses: actions/checkout@v4

      # 2. Set up JDK (make sure version matches your project)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'zulu'

      # 3. Install and configure Gradle directly (no wrapper)
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
        with:
          gradle-version: '4.5' # or whatever version you prefer

      # 4. Build the project
      - name: Build with Gradle
        run: gradle build

  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # 1. Checkout repository
      - uses: actions/checkout@v4

      # 2. Set up JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'zulu'

      # 3. Install Gradle directly
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582
        with:
          gradle-version: '4.5'

      # 4. Generate and submit dependency graph
      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
